name: deploy to heroku
on:
  push:
    branches:
    - 'main'
    # have to change back to 'release' branch before final submission

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'FPAngular'
    steps:
    - name: Checkout Angular code
      uses: actions/checkout@v2
    - name: Setup node-version
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: NPM Install
      run: npm install --legacy-peer-deps
    - name: NPM install Angular
      run: npm install -g --legacy-peer-deps @angular/cli > /dev/null
    - name: NPM build
      run: npm run build
    - name: Delete existing files in server folder
      run: sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_PASS }}@${{ secrets.SSH_HOST }} 'rm -rf /Users/TSL/documents/visa/finalProject/FPServer/src/main/resources/static/*'
    # - name: Compress and copy new files to the server
    #   run: |
    #         cd dist/
    