name: deploy to heroku
on:
  push:
    branches:
    - 'main'
    # have to change back to 'release' branch before final submission

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'FPAngular'
    steps:
    - name: Checkout Angular code
      uses: actions/checkout@v2
    - name: Setup node-version
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: NPM Install
      run: npm install --legacy-peer-deps
    - name: NPM install Angular
      run: npm install -g --legacy-peer-deps @angular/cli > /dev/null
    - name: NPM build
      run: npm run build
    - name: Delete existing files in server folder
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        run:  |
              sudo sshpass -Password ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rm -rf /Users/TSL/documents/visa/finalProject/FPServer/src/main/resources/static/'

    #   run: sudo sshpass -P 1234567890:D -v ssh -o StrictHostKeyChecking=no TSL@127.0.0.1 'rm -rf /Users/TSL/documents/visa/finalProject/FPServer/src/main/resources/static/*'
      # run: sudo sshpass -Password ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rm -rf /Users/TSL/documents/visa/finalProject/FPServer/src/main/resources/static/'
    - name: Copy files over to server
      run : cp -r /Users/tsl/documents/visa/finalproject/FPAngular/dist/fpangular/ /Users/tsl/documents/visa/finalproject/FPServer/src/main/resources/static