name: deploy to heroku
on:
  push:
    branches:
    - 'main'
    # have to change back to 'release' branch before final submission

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'FPAngular'
    steps:
    - name: Checkout Angular code
      uses: actions/checkout@v2
    - name: Setup node-version
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: NPM Install
      run: npm install --legacy-peer-deps
    - name: NPM install Angular
      run: npm install -g --legacy-peer-deps @angular/cli > /dev/null
    - name: NPM build
      run: npm run build
    # - name: Delete existing files in server folder
      # uses: matheusvanzan/sshpass-action@v2
      # with:
      #   host: ${{ secrets.SERVER_HOST }}
      #   user: ${{ secrets.SERVER_USER }}
      #   key: ${{ secrets.SERVER_KEY }}
      #   run:  |
      #         sudo sshpass -Password ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rm -rf /Users/TSL/documents/visa/finalProject/FPServer/src/main/resources/static/'
      # run: sudo sshpass -Password ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rm -rf /Users/TSL/documents/visa/finalProject/FPServer/src/main/resources/static/'
      # run:  |
      #       sudo ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rm -rf /Users/TSL/documents/visa/finalProject/FPServer/src/main/resources/static/'
      #       ${{ secrets.SSH_PASS }}
    - name: Copying files to server
      working-directory: 'VTTP-Final-Project'
      run :  |
             cp -r './FPAngular/dist/fpangular/' './FPServer/src/main/resources/static'
    # - name: Copy DIST files
    #   run :  cp -r './dist/fpangular/'
    # - name: Move files to Server
    #   working-directory: 'FPServer'
    #   run: mv ./src/main/resources/static
        

      


      #       working-directory: FinalProject
      # run :  |
      #        cp -r './FPAngular/dist/fpangular/' './FPServer/src/main/resources/static'