name: deploy to heroku
on:
  push:
    branches:
    - 'main'
    # have to change back to 'release' branch before final submission

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'FPAngular'
    steps:
    - name: Checkout Angular code
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: NPM Install
      run: npm install
    - name: NPM install Angular
      run: npm install -g @angular/cli > /dev/null
    - name: NPM build
      run: npm build
    